Die if .bashrc, .gitconfig, or .hgrc don't 'include' their .khan counterparts
Summary:
If a user runs setup.sh with one of these files already existing on
their system, the setup script leaves them alone.  But that can be
bad, since we need those scripts to include the .khan variants
(.bashrc.khan, etc).  We now die if they don't, and tell the user how
to fix it up manually.

Test Plan:
Ran
   ./setup.sh /var/tmp/setup
Then edited /var/tmp/setup/.bashrc to be the empty file, and reran
   ./setup.sh /var/tmp/setup
and saw
---
Checking system dependencies
This setup script needs your password to install things as root.
Thanks
Installing and updating dotfiles (.bashrc, etc)
FATAL ERROR: /var/tmp/setup/.bashrc does not 'include' .bashrc.khan;  see /home/csilvers/khan/devtools/khan-dotfiles/bashrc.default and add equivalent logic to /var/tmp/setup/.bashrc
FATAL ERROR: Fix this problem and then re-run ./setup.sh
---

Reviewers: benkomalo, alpert

Reviewed By: benkomalo

CC: mattdunnrankin

Differential Revision: http://phabricator.khanacademy.org/D2313